### ISSUE TITLE
Introduce drag over property, to only show items that accept dropped files

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/QuickNav#16]
Create a property for every CommandCollector, that says, whether that command can handle drag dropped files or not. Just a bool.
Then when the user drops a file in, only show those items that allow drag drop.

**Comment by finn-freitag** [comment]
I have extended it a little so that you can specify accepted file types.

**Comment by FrozenAssassine** [comment]
Works as I expected it. Good job ❤️
